# Generated by Django 2.0.6 on 2018-07-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pylog', '0004_auto_20180711_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/uploads/'),
        ),
    ]
