# Generated by Django 2.0.6 on 2018-07-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pylog', '0005_auto_20180712_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/uploads/%Y/%B/%d'),
        ),
    ]
